apiVersion: v2
name: coredns
version: 1.45.3
appVersion: 1.13.1
home: https://coredns.io
icon: https://coredns.io/images/CoreDNS_Colour_Horizontal.png
description: CoreDNS is a DNS server that chains plugins and provides Kubernetes DNS Services
keywords:
  - coredns
  - dns
  - kubedns
sources:
  - https://github.com/coredns/coredns
maintainers:
  - name: mrueg
  - name: haad
  - name: hagaibarel
  - name: shubham-cmyk
type: application
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Align default resources with upstream kubeadm CoreDNS defaults (remove CPU limit, set memory limit to 170Mi, set memory request to 70Mi)
    - kind: added
      description: Add configurable dnsPolicy for deployment
